version: "3.9"
services:
  kubesmas-tree:
    build: ./kubesmas-tree
    working_dir: /go/src
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - "REDIS_HOST=redis:6379"
      - "PORT=8080"

  worker:
    build: ./worker
    depends_on:
      - redis
    environment:
      - "REDIS_HOST=redis:6379"

  redis:
    image: redis
    ports:
      - "6379:6379"
